--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    is_developer boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

create table public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.issues (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    title text not null,
    description text,
    status text not null default 'todo',
    priority text,
    assignee_id bigint,
    due_date date,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    index smallint
);

create table public.issue_notes (
    id bigint generated by default as identity primary key,
    issue_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

-- HRMS: employees. sales_id is nullable and admin-assigned (an employee may
-- exist without a CRM login; never auto-defaulted like companies/deals).
create table public.employees (
    id bigint generated by default as identity primary key,
    sales_id bigint unique,
    first_name text not null,
    last_name text not null,
    email extensions.citext,
    phone text,
    employee_code text,
    department text,
    designation text,
    employment_type text,
    status text not null default 'active',
    date_of_joining date not null default current_date,
    date_of_leaving date,
    avatar jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- HRMS: leave requests. status is a fixed workflow enum (not config-driven,
-- unlike issue statuses), since the app branches on the literal values and
-- RLS enforces them via check constraints and policy "with check" clauses.
create table public.leave_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    leave_type text not null,
    from_date date not null,
    to_date date not null,
    days smallint generated always as ((to_date - from_date) + 1) stored,
    reason text,
    status text not null default 'pending',
    approved_by bigint,
    approved_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint leave_requests_dates_check check (to_date >= from_date),
    constraint leave_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.projects
    add constraint projects_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.issues
    add constraint issues_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;

alter table public.issues
    add constraint issues_assignee_id_fkey foreign key (assignee_id) references public.sales(id);

alter table public.issues
    add constraint issues_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.issue_notes
    add constraint issue_notes_issue_id_fkey foreign key (issue_id) references public.issues(id) on update cascade on delete cascade;

alter table public.issue_notes
    add constraint issue_notes_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.employees
    add constraint employees_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

alter table public.leave_requests
    add constraint leave_requests_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;
alter table public.leave_requests
    add constraint leave_requests_approved_by_fkey foreign key (approved_by) references public.sales(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index issues_project_id_idx on public.issues using btree (project_id);
create index issue_notes_issue_id_idx on public.issue_notes using btree (issue_id);
create unique index employees_employee_code_uq on public.employees (employee_code) where employee_code is not null;
create index leave_requests_employee_id_idx on public.leave_requests using btree (employee_id);
