--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    is_developer boolean not null default false,
    notes_only boolean not null default false,
    is_accounts boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

create table public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    sales_id bigint,
    -- Admin-managed project team, besides admins who bypass this entirely.
    member_ids bigint[] not null default '{}',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.sprints (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name text not null,
    start_date date,
    end_date date,
    status text not null default 'planned',
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint sprints_status_check check (status in ('planned', 'active', 'completed'))
);

create table public.milestones (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name text not null,
    description text,
    due_date date,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create table public.issues (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    title text not null,
    description text,
    status text not null default 'todo',
    priority text,
    assignee_id bigint,
    due_date date,
    start_date date,
    sprint_id bigint,
    milestone_id bigint,
    parent_id bigint,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    index smallint
);

create table public.issue_notes (
    id bigint generated by default as identity primary key,
    issue_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

-- Append-only audit log of issue status transitions, powers the sprint
-- burndown chart. project_id is denormalized from issues (every row
-- already carries it) so callers can filter by a plain equality match.
create table public.issue_status_history (
    id bigint generated by default as identity primary key,
    issue_id bigint not null,
    project_id bigint not null,
    from_status text,
    to_status text not null,
    changed_at timestamp with time zone not null default now()
);

-- HRMS: employees. sales_id is nullable and admin-assigned (an employee may
-- exist without a CRM login; never auto-defaulted like companies/deals).
-- Backs generate_employee_code() (see 02_functions.sql) -- EMP-0001,
-- EMP-0002, ... assigned automatically on insert when not provided.
create sequence if not exists public.employee_code_seq start 1;

create table public.employees (
    id bigint generated by default as identity primary key,
    sales_id bigint unique,
    first_name text not null,
    last_name text not null,
    email extensions.citext,
    phone text,
    employee_code text,
    department text,
    designation text,
    employment_type text,
    status text not null default 'active',
    date_of_joining date not null default current_date,
    date_of_leaving date,
    avatar jsonb,
    date_of_birth date,
    address text,
    emergency_contact_name text,
    emergency_contact_phone text,
    bank_name text,
    bank_account_name text,
    bank_account_number text,
    bank_ifsc text,
    previous_employer text,
    previous_designation text,
    total_experience_years numeric(4,1),
    qualification text,
    background text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- HRMS: leave requests. status is a fixed workflow enum (not config-driven,
-- unlike issue statuses), since the app branches on the literal values and
-- RLS enforces them via check constraints and policy "with check" clauses.
create table public.leave_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    leave_type text not null,
    from_date date not null,
    to_date date not null,
    days smallint generated always as ((to_date - from_date) + 1) stored,
    reason text,
    status text not null default 'pending',
    approved_by bigint,
    approved_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint leave_requests_dates_check check (to_date >= from_date),
    constraint leave_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

-- HRMS: attendance records. No approval workflow in v1 — self can log/edit
-- their own rows freely (join-through RLS to employees.sales_id).
create table public.attendance_records (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    date date not null,
    status text not null default 'present',
    check_in timestamp with time zone,
    check_out timestamp with time zone,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- HRMS: payroll. v1 is intentionally simple (no tax/PF/ESI/TDS engine):
-- basic salary + manual allowance/deduction line items, snapshotted
-- monthly into payslips with trigger-computed totals.
create table public.salary_structures (
    id bigint generated by default as identity primary key,
    employee_id bigint not null unique,
    basic numeric(12,2) not null default 0,
    allowances jsonb not null default '[]',
    deductions jsonb not null default '[]',
    effective_from date not null default current_date,
    updated_at timestamp with time zone not null default now()
);

create table public.payslips (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    month smallint not null,
    year smallint not null,
    basic numeric(12,2) not null default 0,
    allowances jsonb not null default '[]',
    deductions jsonb not null default '[]',
    gross_pay numeric(12,2) not null default 0,
    net_pay numeric(12,2) not null default 0,
    status text not null default 'draft',
    finalized_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint payslips_month_check check (month between 1 and 12),
    constraint payslips_status_check check (status in ('draft', 'finalized'))
);

-- Accounts: personal finance tracking from uploaded bank statements.
-- Fully admin-only, no self-service scoping (unlike HRMS).
create table public.statement_imports (
    id bigint generated by default as identity primary key,
    filename text not null,
    period_from date,
    period_to date,
    transaction_count integer not null default 0,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create table public.transactions (
    id bigint generated by default as identity primary key,
    date date not null,
    description text not null,
    amount numeric(12,2) not null,
    category text,
    balance_after numeric(12,2),
    source text not null default 'manual',
    statement_import_id bigint,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    -- Personal vs. business, tagged per transaction rather than split into
    -- a separate app/DB -- see docs/accounts-roadmap.md.
    scope text not null default 'business',
    -- Which recurring_expenses row this real transaction was matched
    -- against, if any -- see the recurring_expenses table comment below.
    recurring_expense_id bigint,
    constraint transactions_source_check check (source in ('manual', 'statement')),
    constraint transactions_scope_check check (scope in ('business', 'personal'))
);

-- Unavoidable monthly expenses (EMI, class fees, rent, subscriptions) --
-- see docs/accounts-roadmap.md. match_keyword lets statement import review
-- auto-suggest linking a real imported transaction to one of these, same
-- shape as categoryRules keyword matching (matchCategoryRule) -- set once
-- by the user, not learned automatically from bank statement text.
create table public.recurring_expenses (
    id bigint generated by default as identity primary key,
    name text not null,
    amount numeric(12,2) not null,
    category text,
    scope text not null default 'personal',
    due_day integer not null,
    match_keyword text,
    active boolean not null default true,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint recurring_expenses_scope_check check (scope in ('business', 'personal')),
    constraint recurring_expenses_due_day_check check (due_day between 1 and 28)
);

-- Khatabook-style personal lending ledger -- who I've given money to, who's
-- given money to me. See docs/accounts-roadmap.md: loans.transaction_id
-- links to the real transactions row created alongside a loan (offered,
-- not forced -- a cash loan has nothing to link to), so the bank total and
-- the "who owes me" total can't silently disagree.
create table public.people (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

create table public.loans (
    id bigint generated by default as identity primary key,
    person_id bigint not null,
    -- 'given' = I lent them money, they owe me. 'received' = I borrowed
    -- from them, I owe them.
    direction text not null,
    amount numeric(12,2) not null,
    scope text not null default 'personal',
    settled boolean not null default false,
    settled_at timestamp with time zone,
    transaction_id bigint,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint loans_direction_check check (direction in ('given', 'received')),
    constraint loans_scope_check check (scope in ('business', 'personal')),
    constraint loans_amount_check check (amount > 0)
);

-- Actual-vs-budgeted per category per month per scope -- see
-- docs/accounts-roadmap.md. sales_id is audit-trail only (who set it), NOT
-- part of the natural key -- transactions' RLS already means every admin
-- shares one ledger, not a per-admin one.
create table public.budgets (
    id bigint generated by default as identity primary key,
    category text not null,
    scope text not null default 'business',
    month date not null, -- always the 1st of the month
    amount numeric(12,2) not null,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint budgets_scope_check check (scope in ('business', 'personal')),
    constraint budgets_amount_check check (amount > 0),
    unique (category, scope, month)
);

-- Personal notes: Google-Keep-style, self-owned. Unlike every other table
-- here, delete does NOT require admin (private scratch content, not shared
-- business/HR data).
create table public.personal_notes (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    title text,
    content text,
    type text not null default 'note',
    checklist_items jsonb not null default '[]',
    tags bigint[],
    color text,
    pinned boolean not null default false,
    archived_at timestamp with time zone,
    deleted_at timestamp with time zone,
    attachments jsonb[],
    remind_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint personal_notes_type_check check (type in ('note', 'checklist'))
);

-- Personal note version history, snapshotted automatically on meaningful
-- edits (see 04_triggers.sql's snapshot_personal_note_version()).
create table public.personal_note_versions (
    id bigint generated by default as identity primary key,
    note_id bigint not null,
    title text,
    content text,
    type text not null,
    checklist_items jsonb not null default '[]',
    tags bigint[],
    color text,
    created_at timestamp with time zone not null default now()
);

-- Personal note sharing: read-only for the recipient (owner edits, a
-- shared user views).
create table public.personal_note_shares (
    id bigint generated by default as identity primary key,
    note_id bigint not null,
    shared_with_sales_id bigint not null,
    created_at timestamp with time zone not null default now(),
    unique (note_id, shared_with_sales_id)
);

-- Leads: staging area for unqualified/raw contact data, separate from
-- contacts/companies. Funnel: new -> contacted -> qualified/disqualified.
-- Qualifying converts a lead into a real Contact (+ Company/Deal) --
-- the lead row is kept as an audit trail via converted_*_id.
create table public.leads (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    company_name text,
    email text,
    phone text,
    title text,
    source text,
    notes text,
    status text not null default 'new',
    disqualify_reason text,
    assignee_id bigint,
    converted_contact_id bigint,
    converted_company_id bigint,
    converted_deal_id bigint,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint leads_status_check check (status in ('new', 'contacted', 'qualified', 'disqualified'))
);

-- Contact-attempt log: every call/WhatsApp/email attempt a rep makes on a
-- lead, whether or not it got a response -- see the leads table comment
-- above. leads.status still tracks the coarse funnel stage; this tracks the
-- actual outreach history behind it. "Last attempt / how many" is computed
-- live from these rows in leads_summary (see 03_views.sql), not
-- denormalized onto leads itself.
create table public.lead_activities (
    id bigint generated by default as identity primary key,
    lead_id bigint not null,
    sales_id bigint,
    channel text not null,
    outcome text,
    created_at timestamp with time zone not null default now(),
    constraint lead_activities_channel_check check (channel in ('call', 'whatsapp', 'email')),
    constraint lead_activities_outcome_check check (
        outcome is null or outcome in ('no_answer', 'responded', 'wrong_number', 'not_interested', 'callback_later')
    )
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.projects
    add constraint projects_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.sprints
    add constraint sprints_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;

alter table public.milestones
    add constraint milestones_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;

alter table public.issues
    add constraint issues_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;

alter table public.issues
    add constraint issues_sprint_id_fkey foreign key (sprint_id) references public.sprints(id) on delete set null;

alter table public.issues
    add constraint issues_milestone_id_fkey foreign key (milestone_id) references public.milestones(id) on delete set null;

alter table public.issues
    add constraint issues_parent_id_fkey foreign key (parent_id) references public.issues(id) on delete set null;

alter table public.issues
    add constraint issues_assignee_id_fkey foreign key (assignee_id) references public.sales(id);

alter table public.issues
    add constraint issues_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.issue_notes
    add constraint issue_notes_issue_id_fkey foreign key (issue_id) references public.issues(id) on update cascade on delete cascade;

alter table public.issue_notes
    add constraint issue_notes_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.issue_status_history
    add constraint issue_status_history_issue_id_fkey foreign key (issue_id) references public.issues(id) on delete cascade;
alter table public.issue_status_history
    add constraint issue_status_history_project_id_fkey foreign key (project_id) references public.projects(id) on delete cascade;

alter table public.employees
    add constraint employees_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

alter table public.leave_requests
    add constraint leave_requests_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;
alter table public.leave_requests
    add constraint leave_requests_approved_by_fkey foreign key (approved_by) references public.sales(id);

alter table public.attendance_records
    add constraint attendance_records_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;

alter table public.salary_structures
    add constraint salary_structures_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;

alter table public.payslips
    add constraint payslips_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;

alter table public.statement_imports
    add constraint statement_imports_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.transactions
    add constraint transactions_statement_import_id_fkey foreign key (statement_import_id) references public.statement_imports(id) on update cascade on delete set null;
alter table public.transactions
    add constraint transactions_sales_id_fkey foreign key (sales_id) references public.sales(id);
alter table public.transactions
    add constraint transactions_recurring_expense_id_fkey foreign key (recurring_expense_id) references public.recurring_expenses(id) on delete set null;

alter table public.recurring_expenses
    add constraint recurring_expenses_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

alter table public.people
    add constraint people_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

-- restrict, not cascade: a loan is a financial record, not incidental
-- metadata that should vanish along with the person row.
alter table public.loans
    add constraint loans_person_id_fkey foreign key (person_id) references public.people(id) on delete restrict;
alter table public.loans
    add constraint loans_transaction_id_fkey foreign key (transaction_id) references public.transactions(id) on delete set null;
alter table public.loans
    add constraint loans_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

alter table public.budgets
    add constraint budgets_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

alter table public.personal_notes
    add constraint personal_notes_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete cascade;

alter table public.personal_note_versions
    add constraint personal_note_versions_note_id_fkey foreign key (note_id) references public.personal_notes(id) on update cascade on delete cascade;

alter table public.personal_note_shares
    add constraint personal_note_shares_note_id_fkey foreign key (note_id) references public.personal_notes(id) on update cascade on delete cascade;
alter table public.personal_note_shares
    add constraint personal_note_shares_shared_with_sales_id_fkey foreign key (shared_with_sales_id) references public.sales(id) on delete cascade;

alter table public.leads
    add constraint leads_assignee_id_fkey foreign key (assignee_id) references public.sales(id);
alter table public.leads
    add constraint leads_converted_contact_id_fkey foreign key (converted_contact_id) references public.contacts(id) on delete set null;
alter table public.leads
    add constraint leads_converted_company_id_fkey foreign key (converted_company_id) references public.companies(id) on delete set null;
alter table public.leads
    add constraint leads_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;
alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.lead_activities
    add constraint lead_activities_lead_id_fkey foreign key (lead_id) references public.leads(id) on delete cascade;
alter table public.lead_activities
    add constraint lead_activities_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index issues_project_id_idx on public.issues using btree (project_id);
create index sprints_project_id_idx on public.sprints using btree (project_id);
create index milestones_project_id_idx on public.milestones using btree (project_id);
create index issues_parent_id_idx on public.issues using btree (parent_id);
create index issue_notes_issue_id_idx on public.issue_notes using btree (issue_id);
create index issue_status_history_project_id_idx on public.issue_status_history using btree (project_id);
create index issue_status_history_issue_id_idx on public.issue_status_history using btree (issue_id);
create unique index employees_employee_code_uq on public.employees (employee_code) where employee_code is not null;
create index leave_requests_employee_id_idx on public.leave_requests using btree (employee_id);
create unique index attendance_records_employee_date_uq on public.attendance_records (employee_id, date);
create unique index payslips_employee_month_year_uq on public.payslips (employee_id, month, year);
create index transactions_date_idx on public.transactions using btree (date);
create index transactions_statement_import_id_idx on public.transactions using btree (statement_import_id);
create index personal_notes_sales_id_idx on public.personal_notes using btree (sales_id);
create index personal_note_versions_note_id_idx on public.personal_note_versions using btree (note_id);
create index personal_note_shares_note_id_idx on public.personal_note_shares using btree (note_id);
create index leads_status_idx on public.leads using btree (status);
create index leads_assignee_id_idx on public.leads using btree (assignee_id);
create index lead_activities_lead_id_idx on public.lead_activities using btree (lead_id);
create index loans_person_id_idx on public.loans using btree (person_id);
