-- Server-to-server OAuth refresh tokens (Google Drive, to start).
-- service_role only.
create table public.oauth_tokens (
    id bigint generated by default as identity primary key,
    provider text not null,
    refresh_token text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint oauth_tokens_provider_unique unique (provider)
);

alter table public.oauth_tokens enable row level security;

grant all on table public.oauth_tokens to service_role;
grant all on sequence public.oauth_tokens_id_seq to service_role;
