--
-- PM: real sprint burndown chart (#87). #67 shipped a current-state
-- progress bar (done/total) as an honest substitute -- a real burndown
-- needs to know remaining-open-count *per day*, which needs history
-- this schema didn't track. This adds that history and starts logging
-- it going forward.
--
-- project_id is denormalized onto this table (issues already carries it
-- on every row, no extra lookup needed) specifically so the chart can
-- filter by a plain equality match -- the same {field: value} filter
-- shape already proven everywhere else in this app -- rather than an
-- issue_id "in" list filter that isn't used anywhere else in this
-- codebase and wasn't worth being the first place to find out whether
-- it's supported.
--

create table public.issue_status_history (
    id bigint generated by default as identity primary key,
    issue_id bigint not null,
    project_id bigint not null,
    from_status text,
    to_status text not null,
    changed_at timestamp with time zone not null default now()
);

alter table public.issue_status_history
    add constraint issue_status_history_issue_id_fkey foreign key (issue_id) references public.issues(id) on delete cascade;
alter table public.issue_status_history
    add constraint issue_status_history_project_id_fkey foreign key (project_id) references public.projects(id) on delete cascade;

create index issue_status_history_project_id_idx on public.issue_status_history using btree (project_id);
create index issue_status_history_issue_id_idx on public.issue_status_history using btree (issue_id);

alter table public.issue_status_history enable row level security;
create policy "PM access select" on public.issue_status_history for select to authenticated using (public.has_pm_access());
create policy "PM access insert" on public.issue_status_history for insert to authenticated with check (public.has_pm_access());
-- No update/delete policies -- this is an append-only audit log, same
-- posture as activity_log elsewhere in this schema.

grant all on table public.issue_status_history to anon;
grant all on table public.issue_status_history to authenticated;
grant all on table public.issue_status_history to service_role;
grant all on sequence public.issue_status_history_id_seq to anon;
grant all on sequence public.issue_status_history_id_seq to authenticated;
grant all on sequence public.issue_status_history_id_seq to service_role;

-- Not SECURITY DEFINER -- same convention as
-- snapshot_personal_note_version() (see 02_functions.sql): runs as the
-- acting user, relying on this table's own insert policy (has_pm_access,
-- same as issues itself) rather than bypassing RLS.
create or replace function public.log_issue_status_change() returns trigger
    language plpgsql
    set search_path = ''
    as $$
begin
  if tg_op = 'INSERT' then
    insert into public.issue_status_history (issue_id, project_id, from_status, to_status)
    values (new.id, new.project_id, null, new.status);
  elsif tg_op = 'UPDATE' and old.status is distinct from new.status then
    insert into public.issue_status_history (issue_id, project_id, from_status, to_status)
    values (new.id, new.project_id, old.status, new.status);
  end if;
  return new;
end;
$$;

create or replace trigger log_issue_status_change_trigger
    after insert or update on public.issues
    for each row execute function public.log_issue_status_change();

-- Backfill a day-0 baseline for every issue that already existed before
-- this migration, so a sprint with pre-existing issues still has
-- *something* to chart -- not a true blow-by-blow history for issues
-- that changed status multiple times before today, which can't be
-- reconstructed retroactively, but an honest "created with status X at
-- time T" starting point rather than an empty chart.
insert into public.issue_status_history (issue_id, project_id, from_status, to_status, changed_at)
select id, project_id, null, status, created_at from public.issues;
