-- Actual-vs-budgeted per category per month per scope -- see
-- docs/accounts-roadmap.md. sales_id is audit-trail only (who set it), NOT
-- part of the natural key: transactions' own RLS is is_admin() for every
-- row (every admin already shares one ledger, not a per-admin one), so
-- sales_id in the unique constraint would let two different admins each
-- set a different "valid" budget for the same category+scope+month --
-- caught in review on this exact mistake for recurring_expenses' sibling
-- design earlier, not repeating it here.
create table public.budgets (
    id bigint generated by default as identity primary key,
    category text not null,
    scope text not null default 'business',
    month date not null, -- always the 1st of the month
    amount numeric(12,2) not null,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint budgets_scope_check check (scope in ('business', 'personal')),
    constraint budgets_amount_check check (amount > 0),
    unique (category, scope, month)
);
alter table public.budgets
    add constraint budgets_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

create or replace trigger set_budgets_sales_id_trigger before insert on public.budgets
    for each row execute function public.set_sales_id_default();

alter table public.budgets enable row level security;

-- Same "Admin only" shape as every other Accounts table.
create policy "Admin only" on public.budgets for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant all on table public.budgets to anon;
grant all on table public.budgets to authenticated;
grant all on table public.budgets to service_role;
grant all on sequence public.budgets_id_seq to anon;
grant all on sequence public.budgets_id_seq to authenticated;
grant all on sequence public.budgets_id_seq to service_role;
