-- Adds the Projects/Issues module: a simple project container plus issues
-- shown on a Kanban board grouped by status, with a comments/activity feed
-- on each issue. Access is role-based via has_pm_access() (admin or
-- developer) rather than per-user sales_id scoping — every admin/developer
-- sees every project and issue.

create table public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.issues (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    title text not null,
    description text,
    status text not null default 'todo',
    priority text,
    assignee_id bigint,
    due_date date,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    index smallint
);

create table public.issue_notes (
    id bigint generated by default as identity primary key,
    issue_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

alter table public.projects
    add constraint projects_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.issues
    add constraint issues_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;
alter table public.issues
    add constraint issues_assignee_id_fkey foreign key (assignee_id) references public.sales(id);
alter table public.issues
    add constraint issues_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.issue_notes
    add constraint issue_notes_issue_id_fkey foreign key (issue_id) references public.issues(id) on update cascade on delete cascade;
alter table public.issue_notes
    add constraint issue_notes_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index issues_project_id_idx on public.issues using btree (project_id);
create index issue_notes_issue_id_idx on public.issue_notes using btree (issue_id);

-- sales_id defaults (mirrors set_sales_id_default used on companies/deals/etc.)
create or replace trigger set_project_sales_id_trigger
    before insert on public.projects
    for each row execute function public.set_sales_id_default();

create or replace trigger set_issue_sales_id_trigger
    before insert on public.issues
    for each row execute function public.set_sales_id_default();

create or replace trigger set_issue_notes_sales_id_trigger
    before insert on public.issue_notes
    for each row execute function public.set_sales_id_default();

-- Reuse the existing generic attachment-cleanup trigger function.
create or replace trigger on_issue_notes_attachments_updated_delete_note_attachments
    after update on public.issue_notes
    for each row
    when (old.attachments is distinct from new.attachments)
    execute function public.cleanup_note_attachments();

create or replace trigger on_issue_notes_deleted_delete_note_attachments
    after delete on public.issue_notes
    for each row execute function public.cleanup_note_attachments();

-- nb_issues summary view, mirroring companies_summary's nb_deals/nb_contacts
create or replace view public.projects_summary with (security_invoker = on) as
select
    p.id,
    p.name,
    p.description,
    p.sales_id,
    p.created_at,
    p.updated_at,
    count(distinct i.id) as nb_issues
from public.projects p
    left join public.issues i on p.id = i.project_id
group by p.id;

-- RLS
alter table public.projects enable row level security;
alter table public.issues enable row level security;
alter table public.issue_notes enable row level security;

create policy "PM access select" on public.projects for select to authenticated using (public.has_pm_access());
create policy "PM access insert" on public.projects for insert to authenticated with check (public.has_pm_access());
create policy "PM access update" on public.projects for update to authenticated using (public.has_pm_access()) with check (public.has_pm_access());
create policy "Admin delete only" on public.projects for delete to authenticated using (public.is_admin());

create policy "PM access select" on public.issues for select to authenticated using (public.has_pm_access());
create policy "PM access insert" on public.issues for insert to authenticated with check (public.has_pm_access());
create policy "PM access update" on public.issues for update to authenticated using (public.has_pm_access()) with check (public.has_pm_access());
create policy "Admin delete only" on public.issues for delete to authenticated using (public.is_admin());

create policy "PM access select" on public.issue_notes for select to authenticated using (public.has_pm_access());
create policy "PM access insert" on public.issue_notes for insert to authenticated with check (public.has_pm_access());
create policy "PM access update" on public.issue_notes for update to authenticated using (public.has_pm_access()) with check (public.has_pm_access());
create policy "Admin delete only" on public.issue_notes for delete to authenticated using (public.is_admin());

-- Grants
grant all on table public.projects to anon, authenticated, service_role;
grant all on table public.issues to anon, authenticated, service_role;
grant all on table public.issue_notes to anon, authenticated, service_role;
grant all on table public.projects_summary to anon, authenticated, service_role;
grant all on sequence public.projects_id_seq to anon, authenticated, service_role;
grant all on sequence public.issues_id_seq to anon, authenticated, service_role;
grant all on sequence public.issue_notes_id_seq to anon, authenticated, service_role;
