-- Unavoidable monthly expenses (EMI, class fees, rent, subscriptions) --
-- see docs/accounts-roadmap.md. Two jobs: (1) an "already spoken for this
-- month" total on the dashboard, computed from active rows here, before
-- the user budgets the rest; (2) a match_keyword that lets statement
-- import review auto-suggest linking a real imported transaction to one of
-- these, same shape as the existing categoryRules keyword matching
-- (matchCategoryRule/categoryRuleMatcher.ts) -- set once by the user, not
-- learned automatically from bank statement text (UPI/NEFT reference
-- numbers change every occurrence, so pattern-matching on raw description
-- text alone isn't reliable -- see the roadmap doc's reasoning).
create table public.recurring_expenses (
    id bigint generated by default as identity primary key,
    name text not null,
    amount numeric(12,2) not null,
    category text,
    scope text not null default 'personal',
    due_day integer not null,
    match_keyword text,
    active boolean not null default true,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint recurring_expenses_scope_check check (scope in ('business', 'personal')),
    constraint recurring_expenses_due_day_check check (due_day between 1 and 28)
);
alter table public.recurring_expenses
    add constraint recurring_expenses_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

-- Which recurring expense a real transaction was matched against (manually
-- confirmed, whether by accepting an auto-suggested match or picking one
-- directly) -- lets the dashboard compare "expected" vs "actually posted"
-- for the month, not just show the recurring_expenses list on its own.
alter table public.transactions add column recurring_expense_id bigint;
alter table public.transactions
    add constraint transactions_recurring_expense_id_fkey foreign key (recurring_expense_id) references public.recurring_expenses(id) on delete set null;

alter table public.recurring_expenses enable row level security;

-- Same "Admin only" shape as transactions/statement_imports -- Accounts is
-- fully admin-only in this app, not self-service (see ACCOUNTS_RESOURCES
-- in canAccess.ts).
create policy "Admin only" on public.recurring_expenses for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant all on table public.recurring_expenses to anon;
grant all on table public.recurring_expenses to authenticated;
grant all on table public.recurring_expenses to service_role;
grant all on sequence public.recurring_expenses_id_seq to anon;
grant all on sequence public.recurring_expenses_id_seq to authenticated;
grant all on sequence public.recurring_expenses_id_seq to service_role;
