--
-- PM: milestones (#68). A single-date target per project, distinct from
-- sprints (a date *range*) -- name, description, due_date. Same
-- has_pm_access() RLS pattern as projects/issues/sprints.
--

create table public.milestones (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name text not null,
    description text,
    due_date date,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

alter table public.milestones
    add constraint milestones_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;

create index milestones_project_id_idx on public.milestones using btree (project_id);

create or replace trigger set_milestone_sales_id_trigger
    before insert on public.milestones
    for each row execute function public.set_sales_id_default();

alter table public.milestones enable row level security;
create policy "PM access select" on public.milestones for select to authenticated using (public.has_pm_access());
create policy "PM access insert" on public.milestones for insert to authenticated with check (public.has_pm_access());
create policy "PM access update" on public.milestones for update to authenticated using (public.has_pm_access()) with check (public.has_pm_access());
create policy "Admin delete only" on public.milestones for delete to authenticated using (public.is_admin());

grant all on table public.milestones to anon;
grant all on table public.milestones to authenticated;
grant all on table public.milestones to service_role;
grant all on sequence public.milestones_id_seq to anon;
grant all on sequence public.milestones_id_seq to authenticated;
grant all on sequence public.milestones_id_seq to service_role;

alter table public.issues add column milestone_id bigint;
alter table public.issues
    add constraint issues_milestone_id_fkey foreign key (milestone_id) references public.milestones(id) on delete set null;
