-- Khatabook-style personal lending ledger -- who I've given money to, who's
-- given money to me. See docs/accounts-roadmap.md: this is NOT a parallel
-- money-tracking system next to `transactions` -- giving/receiving a loan
-- is a real cash event, so loans.transaction_id links to the actual
-- transactions row created alongside it (offered, not forced -- a cash
-- loan with nothing going through the bank has nothing to link to). The
-- bank total and "who owes me" total would otherwise silently disagree the
-- first time someone forgets to keep both in sync by hand.
create table public.people (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);
alter table public.people
    add constraint people_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

create table public.loans (
    id bigint generated by default as identity primary key,
    person_id bigint not null,
    -- 'given' = I lent them money, they owe me. 'received' = I borrowed
    -- from them, I owe them.
    direction text not null,
    amount numeric(12,2) not null,
    scope text not null default 'personal',
    settled boolean not null default false,
    settled_at timestamp with time zone,
    transaction_id bigint,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint loans_direction_check check (direction in ('given', 'received')),
    constraint loans_scope_check check (scope in ('business', 'personal')),
    constraint loans_amount_check check (amount > 0)
);
alter table public.loans
    -- restrict, not cascade: a loan is a financial record, not incidental
    -- metadata that should vanish along with the person row (there's no
    -- delete UI for people today, but this protects against one added
    -- later, or a direct Supabase Studio delete, silently erasing loan
    -- history -- including already-settled loans -- with no confirmation
    -- that financial records are being destroyed).
    add constraint loans_person_id_fkey foreign key (person_id) references public.people(id) on delete restrict;
alter table public.loans
    add constraint loans_transaction_id_fkey foreign key (transaction_id) references public.transactions(id) on delete set null;
alter table public.loans
    add constraint loans_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;
create index loans_person_id_idx on public.loans using btree (person_id);

create or replace trigger set_people_sales_id_trigger before insert on public.people
    for each row execute function public.set_sales_id_default();
create or replace trigger set_loans_sales_id_trigger before insert on public.loans
    for each row execute function public.set_sales_id_default();

alter table public.people enable row level security;
alter table public.loans enable row level security;

-- Same "Admin only" shape as every other Accounts table (transactions,
-- statement_imports, recurring_expenses) -- Accounts is fully admin-only
-- in this app, not self-service.
create policy "Admin only" on public.people for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin only" on public.loans for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant all on table public.people to anon;
grant all on table public.people to authenticated;
grant all on table public.people to service_role;
grant all on sequence public.people_id_seq to anon;
grant all on sequence public.people_id_seq to authenticated;
grant all on sequence public.people_id_seq to service_role;

grant all on table public.loans to anon;
grant all on table public.loans to authenticated;
grant all on table public.loans to service_role;
grant all on sequence public.loans_id_seq to anon;
grant all on sequence public.loans_id_seq to authenticated;
grant all on sequence public.loans_id_seq to service_role;
