-- 1. Marketing role -- same access as a plain sales rep today (no RLS/
-- canAccess changes needed for that), but a real distinct role flag for
-- labeling and future tightening.
alter table public.sales add column is_marketing boolean not null default false;

-- 2. Assignments -- cross-team task delegation, separate from the
-- existing contact-linked `tasks` table. Visible to its creator, its
-- assignee, or an admin; not gated by role, so it works the same for
-- every role except notes-only (kept out at the canAccess layer).
create table public.assignments (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    status text not null default 'todo',
    priority text,
    due_date date,
    assignee_id bigint not null,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint assignments_status_check check (status in ('todo', 'in_progress', 'done')),
    constraint assignments_priority_check check (priority is null or priority in ('low', 'medium', 'high'))
);
alter table public.assignments
    add constraint assignments_assignee_id_fkey foreign key (assignee_id) references public.sales(id) on delete restrict;
alter table public.assignments
    add constraint assignments_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;
create index assignments_assignee_id_idx on public.assignments using btree (assignee_id);

create or replace trigger set_assignment_sales_id_trigger before insert on public.assignments
    for each row execute function public.set_sales_id_default();

alter table public.assignments enable row level security;
create policy "Select own, assigned, or admin" on public.assignments for select to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id() or assignee_id = public.current_sales_id()
);
create policy "Insert own or admin" on public.assignments for insert to authenticated with check (
    public.is_admin() or sales_id = public.current_sales_id()
);
create policy "Update own, assigned, or admin" on public.assignments for update to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id() or assignee_id = public.current_sales_id()
) with check (
    public.is_admin() or sales_id = public.current_sales_id() or assignee_id = public.current_sales_id()
);
create policy "Admin delete only" on public.assignments for delete to authenticated using (public.is_admin());

grant all on table public.assignments to anon;
grant all on table public.assignments to authenticated;
grant all on table public.assignments to service_role;
grant all on sequence public.assignments_id_seq to anon;
grant all on sequence public.assignments_id_seq to authenticated;
grant all on sequence public.assignments_id_seq to service_role;
