--
-- Accounts: personal finance tracking from uploaded bank statements.
-- Fully admin-only (no self-service scoping, unlike HRMS) — the user
-- explicitly chose admin-only visibility for this module.
--

create table public.statement_imports (
    id bigint generated by default as identity primary key,
    filename text not null,
    period_from date,
    period_to date,
    transaction_count integer not null default 0,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

alter table public.statement_imports
    add constraint statement_imports_sales_id_fkey foreign key (sales_id) references public.sales(id);

create trigger set_statement_import_sales_id_trigger before insert on public.statement_imports
    for each row execute function public.set_sales_id_default();

create table public.transactions (
    id bigint generated by default as identity primary key,
    date date not null,
    description text not null,
    amount numeric(12,2) not null,
    category text,
    balance_after numeric(12,2),
    source text not null default 'manual',
    statement_import_id bigint,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint transactions_source_check check (source in ('manual', 'statement'))
);

alter table public.transactions
    add constraint transactions_statement_import_id_fkey foreign key (statement_import_id) references public.statement_imports(id) on update cascade on delete set null;
alter table public.transactions
    add constraint transactions_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index transactions_date_idx on public.transactions using btree (date);
create index transactions_statement_import_id_idx on public.transactions using btree (statement_import_id);

create trigger set_transaction_sales_id_trigger before insert on public.transactions
    for each row execute function public.set_sales_id_default();

alter table public.statement_imports enable row level security;
alter table public.transactions enable row level security;

create policy "Admin only" on public.statement_imports for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin only" on public.transactions for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant all on table public.statement_imports to anon;
grant all on table public.statement_imports to authenticated;
grant all on table public.statement_imports to service_role;

grant all on table public.transactions to anon;
grant all on table public.transactions to authenticated;
grant all on table public.transactions to service_role;

grant all on sequence public.statement_imports_id_seq to anon;
grant all on sequence public.statement_imports_id_seq to authenticated;
grant all on sequence public.statement_imports_id_seq to service_role;

grant all on sequence public.transactions_id_seq to anon;
grant all on sequence public.transactions_id_seq to authenticated;
grant all on sequence public.transactions_id_seq to service_role;
