--
-- HRMS: Payroll
-- v1 is intentionally simple: no tax/PF/ESI/TDS engine. Per-employee basic
-- salary plus manual allowance/deduction line items, snapshotted monthly
-- into payslips with trigger-computed totals (never trust client math for
-- money). Fully admin-managed writes; employees get read-only access to
-- their own rows.
--

create table public.salary_structures (
    id bigint generated by default as identity primary key,
    employee_id bigint not null unique,
    basic numeric(12,2) not null default 0,
    allowances jsonb not null default '[]',
    deductions jsonb not null default '[]',
    effective_from date not null default current_date,
    updated_at timestamp with time zone not null default now()
);

alter table public.salary_structures
    add constraint salary_structures_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;

create table public.payslips (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    month smallint not null,
    year smallint not null,
    basic numeric(12,2) not null default 0,
    allowances jsonb not null default '[]',
    deductions jsonb not null default '[]',
    gross_pay numeric(12,2) not null default 0,
    net_pay numeric(12,2) not null default 0,
    status text not null default 'draft',
    finalized_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint payslips_month_check check (month between 1 and 12),
    constraint payslips_status_check check (status in ('draft', 'finalized'))
);

alter table public.payslips
    add constraint payslips_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;

create unique index payslips_employee_month_year_uq on public.payslips (employee_id, month, year);

create or replace function public.calculate_payslip_totals()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  allowances_total numeric(12,2);
  deductions_total numeric(12,2);
begin
  select coalesce(sum((elem->>'amount')::numeric), 0) into allowances_total
    from jsonb_array_elements(coalesce(new.allowances, '[]'::jsonb)) elem;
  select coalesce(sum((elem->>'amount')::numeric), 0) into deductions_total
    from jsonb_array_elements(coalesce(new.deductions, '[]'::jsonb)) elem;
  new.gross_pay := new.basic + allowances_total;
  new.net_pay := new.basic + allowances_total - deductions_total;
  return new;
end;
$$;

create trigger calculate_payslip_totals_trigger
    before insert or update on public.payslips
    for each row execute function public.calculate_payslip_totals();

alter table public.salary_structures enable row level security;
alter table public.payslips enable row level security;

create policy "Select own or admin" on public.salary_structures for select to authenticated
    using (public.is_admin() or exists (
        select 1 from public.employees e where e.id = salary_structures.employee_id and e.sales_id = public.current_sales_id()
    ));
create policy "Admin write only" on public.salary_structures for insert to authenticated with check (public.is_admin());
create policy "Admin update only" on public.salary_structures for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin delete only" on public.salary_structures for delete to authenticated using (public.is_admin());

create policy "Select own or admin" on public.payslips for select to authenticated
    using (public.is_admin() or exists (
        select 1 from public.employees e where e.id = payslips.employee_id and e.sales_id = public.current_sales_id()
    ));
create policy "Admin write only" on public.payslips for insert to authenticated with check (public.is_admin());
create policy "Admin update only" on public.payslips for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin delete only" on public.payslips for delete to authenticated using (public.is_admin());

grant all on function public.calculate_payslip_totals() to anon;
grant all on function public.calculate_payslip_totals() to authenticated;
grant all on function public.calculate_payslip_totals() to service_role;

grant all on table public.salary_structures to anon;
grant all on table public.salary_structures to authenticated;
grant all on table public.salary_structures to service_role;

grant all on table public.payslips to anon;
grant all on table public.payslips to authenticated;
grant all on table public.payslips to service_role;

grant all on sequence public.salary_structures_id_seq to anon;
grant all on sequence public.salary_structures_id_seq to authenticated;
grant all on sequence public.salary_structures_id_seq to service_role;

grant all on sequence public.payslips_id_seq to anon;
grant all on sequence public.payslips_id_seq to authenticated;
grant all on sequence public.payslips_id_seq to service_role;
