-- Adds a "photographer" tenant concept: each photographer gets their
-- own Drive subfolder, and each of their client galleries gets a
-- subfolder under that. (Only one demo gallery existed with no photos
-- -- deleted directly rather than backfilled, no real data at stake.)
create table public.photographers (
    id bigint generated by default as identity primary key,
    name text not null,
    -- Cached Drive folder id for this photographer, created on first upload.
    drive_folder_id text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.photo_galleries
    add column photographer_id bigint not null references public.photographers(id) on delete cascade,
    -- Cached Drive subfolder id for this gallery (under the
    -- photographer's own folder), created on first upload.
    add column drive_folder_id text;

alter table public.photographers
    add constraint photographers_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

create index photo_galleries_photographer_id_idx on public.photo_galleries using btree (photographer_id);

alter table public.photographers enable row level security;

create policy "Team access, not notes-only" on public.photographers for select to authenticated using (not public.is_notes_only());
create policy "Team insert, not notes-only" on public.photographers for insert to authenticated with check (not public.is_notes_only());
create policy "Team update, not notes-only" on public.photographers for update to authenticated using (not public.is_notes_only()) with check (not public.is_notes_only());
create policy "Admin delete only" on public.photographers for delete to authenticated using (public.is_admin());

create trigger set_photographer_sales_id_trigger
    before insert on public.photographers
    for each row execute function public.set_sales_id_default();

grant all on table public.photographers to authenticated;
grant all on table public.photographers to service_role;
revoke all on table public.photographers from anon;

grant all on sequence public.photographers_id_seq to authenticated;
grant all on sequence public.photographers_id_seq to service_role;
revoke all on sequence public.photographers_id_seq from anon;
