--
-- Leads: a staging area for unqualified/raw contact data, separate from
-- contacts/companies. A lead moves through a simple funnel (new ->
-- contacted -> qualified or disqualified). Qualifying a lead converts it
-- into a real Contact (+ Company if given, + Deal if given) -- the lead
-- row itself is kept (not deleted) as an audit trail of where that
-- contact/company/deal came from, via the converted_*_id columns.
--
-- Self-service scoped like contacts/companies/deals (owner or assignee, or
-- admin) -- NOT admin-only, since any sales rep should be able to work
-- leads assigned to them, not just admins.
--

create table public.leads (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    company_name text,
    email text,
    phone text,
    title text,
    source text,
    notes text,
    status text not null default 'new',
    disqualify_reason text,
    assignee_id bigint,
    converted_contact_id bigint,
    converted_company_id bigint,
    converted_deal_id bigint,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint leads_status_check check (status in ('new', 'contacted', 'qualified', 'disqualified'))
);

alter table public.leads
    add constraint leads_assignee_id_fkey foreign key (assignee_id) references public.sales(id);
alter table public.leads
    add constraint leads_converted_contact_id_fkey foreign key (converted_contact_id) references public.contacts(id) on delete set null;
alter table public.leads
    add constraint leads_converted_company_id_fkey foreign key (converted_company_id) references public.companies(id) on delete set null;
alter table public.leads
    add constraint leads_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;
alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index leads_status_idx on public.leads using btree (status);
create index leads_assignee_id_idx on public.leads using btree (assignee_id);

create trigger set_lead_sales_id_trigger before insert on public.leads
    for each row execute function public.set_sales_id_default();

alter table public.leads enable row level security;

create policy "Select own, assignee, or admin" on public.leads for select to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id() or assignee_id = public.current_sales_id()
);
create policy "Insert own or admin" on public.leads for insert to authenticated with check (
    public.is_admin() or sales_id = public.current_sales_id()
);
create policy "Update own, assignee, or admin" on public.leads for update to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id() or assignee_id = public.current_sales_id()
) with check (
    public.is_admin() or sales_id = public.current_sales_id() or assignee_id = public.current_sales_id()
);
create policy "Admin delete only" on public.leads for delete to authenticated using (public.is_admin());

grant all on table public.leads to anon, authenticated, service_role;
grant all on sequence public.leads_id_seq to anon, authenticated, service_role;
