--
-- Personal Notes: sharing with specific users. Read-only for the
-- recipient in v1 (the owner edits; a shared user views) -- widens
-- personal_notes' select policy only, no update/delete grant change.
--

create table public.personal_note_shares (
    id bigint generated by default as identity primary key,
    note_id bigint not null,
    shared_with_sales_id bigint not null,
    created_at timestamp with time zone not null default now(),
    unique (note_id, shared_with_sales_id)
);

alter table public.personal_note_shares
    add constraint personal_note_shares_note_id_fkey foreign key (note_id) references public.personal_notes(id) on update cascade on delete cascade;
alter table public.personal_note_shares
    add constraint personal_note_shares_shared_with_sales_id_fkey foreign key (shared_with_sales_id) references public.sales(id) on delete cascade;

create index personal_note_shares_note_id_idx on public.personal_note_shares using btree (note_id);

alter table public.personal_note_shares enable row level security;

create policy "Owner, recipient, or admin can view a share" on public.personal_note_shares for select to authenticated using (
    public.is_admin()
    or shared_with_sales_id = public.current_sales_id()
    or exists (select 1 from public.personal_notes pn where pn.id = personal_note_shares.note_id and pn.sales_id = public.current_sales_id())
);
create policy "Owner or admin manages shares" on public.personal_note_shares for insert to authenticated with check (
    public.is_admin() or exists (select 1 from public.personal_notes pn where pn.id = note_id and pn.sales_id = public.current_sales_id())
);
create policy "Owner or admin removes shares" on public.personal_note_shares for delete to authenticated using (
    public.is_admin() or exists (select 1 from public.personal_notes pn where pn.id = personal_note_shares.note_id and pn.sales_id = public.current_sales_id())
);

-- Widen personal_notes visibility to shared recipients.
drop policy "Select own or admin" on public.personal_notes;
create policy "Select own, shared, or admin" on public.personal_notes for select to authenticated using (
    public.is_admin()
    or sales_id = public.current_sales_id()
    or exists (select 1 from public.personal_note_shares ps where ps.note_id = personal_notes.id and ps.shared_with_sales_id = public.current_sales_id())
);

grant all on table public.personal_note_shares to anon;
grant all on table public.personal_note_shares to authenticated;
grant all on table public.personal_note_shares to service_role;

grant all on sequence public.personal_note_shares_id_seq to anon;
grant all on sequence public.personal_note_shares_id_seq to authenticated;
grant all on sequence public.personal_note_shares_id_seq to service_role;
