-- Contact-attempt log for leads: every call/WhatsApp/email attempt a rep
-- makes gets its own row here, whether or not the lead responded -- so
-- "we tried and got nothing" is a real, visible record instead of
-- indistinguishable from "never touched". `leads.status` still tracks the
-- coarse funnel stage; this table tracks the actual outreach history behind
-- it.
create table public.lead_activities (
    id bigint generated by default as identity primary key,
    lead_id bigint not null,
    sales_id bigint,
    channel text not null,
    outcome text,
    created_at timestamp with time zone not null default now(),
    constraint lead_activities_channel_check check (channel in ('call', 'whatsapp', 'email')),
    constraint lead_activities_outcome_check check (
        outcome is null or outcome in ('no_answer', 'responded', 'wrong_number', 'not_interested', 'callback_later')
    )
);
alter table public.lead_activities
    add constraint lead_activities_lead_id_fkey foreign key (lead_id) references public.leads(id) on delete cascade;
alter table public.lead_activities
    add constraint lead_activities_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;
create index lead_activities_lead_id_idx on public.lead_activities using btree (lead_id);

create or replace trigger set_lead_activities_sales_id_trigger before insert on public.lead_activities
    for each row execute function public.set_sales_id_default();

-- "Last attempt / how many" is computed live in leads_summary below (same
-- pattern as companies_summary's nb_deals/nb_contacts, contacts_summary's
-- nb_tasks, projects_summary's nb_issues -- this codebase's established
-- shape for "count of related child rows shown on the parent"), not
-- maintained as a denormalized column via an insert/delete/update trigger.
-- A trigger-maintained column was the first draft here and was wrong: it's
-- write amplification (every attempt logged also updates leads) and a
-- second source of truth that can drift from the real rows (an UPDATE that
-- ever moved lead_activities.lead_id between leads, which the RLS policy
-- below has to permit, would leave both leads' cached numbers stale with
-- nothing to self-heal them). A view has no such gap -- it's always exactly
-- what the rows say, on every read.
create or replace view public.leads_summary with (security_invoker = on) as
select
    l.*,
    count(la.id) as contact_attempt_count,
    max(la.created_at) as last_contact_attempt_at
from public.leads l
    left join public.lead_activities la on la.lead_id = l.id
group by l.id;

-- Reused by every lead_activities policy below instead of repeating the
-- "does this lead belong to me, or am I its assignee" EXISTS-join four
-- times over -- same reason owns_personal_note() exists for personal_notes.
-- SECURITY DEFINER so evaluating it doesn't re-trigger leads' own policy.
create or replace function public.can_access_lead(p_lead_id bigint) returns boolean
    language sql stable security definer
    set search_path = ''
    as $$
  select exists (
    select 1 from public.leads l
    where l.id = p_lead_id
      and (l.sales_id = public.current_sales_id() or l.assignee_id = public.current_sales_id())
  );
$$;

alter table public.lead_activities enable row level security;

-- Same "own, assignee, or admin" visibility as leads itself, and -- like
-- every other sales-data child-log table (contact_notes, deal_notes, tasks,
-- deals all block both roles in their insert policy, literally named
-- "Block developer or notes-only create") -- developers get zero write
-- access here too, not just notes-only users. A developer could in
-- principle be set as a lead's assignee_id (LeadInputs' assignee picker
-- isn't role-filtered), so the ownership check alone isn't enough to keep
-- that invariant true at the database layer.
create policy "Select own, assignee, or admin" on public.lead_activities for select to authenticated using (
    public.is_admin() or public.can_access_lead(lead_id)
);
-- The "sales_id is null or sales_id = current_sales_id()" clause matters as
-- much as the lead-access check: without it, a rep who can see a lead could
-- still submit an explicit sales_id for a *different* rep, falsely
-- attributing (or stealing credit for) a contact attempt -- undermining the
-- one thing this table exists to make trustworthy. set_sales_id_default()
-- only fills sales_id in when it's null, it doesn't overwrite an explicit
-- value, so this has to be enforced here too, not left to the trigger.
create policy "Insert own, assignee, or admin, not notes-only or developer" on public.lead_activities for insert to authenticated with check (
    not public.is_notes_only()
    and not public.is_developer()
    and (sales_id is null or sales_id = public.current_sales_id() or public.is_admin())
    and (public.is_admin() or public.can_access_lead(lead_id))
);
create policy "Update own, assignee, or admin, not developer" on public.lead_activities for update to authenticated using (
    public.is_admin() or public.can_access_lead(lead_id)
) with check (
    public.is_admin()
    or (
        not public.is_developer()
        and (sales_id is null or sales_id = public.current_sales_id())
        and public.can_access_lead(lead_id)
    )
);
create policy "Admin delete only" on public.lead_activities for delete to authenticated using (public.is_admin());

grant all on table public.lead_activities to anon;
grant all on table public.lead_activities to authenticated;
grant all on table public.lead_activities to service_role;
grant all on sequence public.lead_activities_id_seq to anon;
grant all on sequence public.lead_activities_id_seq to authenticated;
grant all on sequence public.lead_activities_id_seq to service_role;

grant all on table public.leads_summary to anon;
grant all on table public.leads_summary to authenticated;
grant all on table public.leads_summary to service_role;
