--
-- HRMS: Employees
-- Adds the employees table, the foundation for the HRMS module (Employees,
-- Leave, Attendance, Payroll). An employee may or may not have a CRM login:
-- sales_id is nullable and admin-assigned (never auto-defaulted from the
-- inserting user, unlike companies/deals/projects), since an HR admin
-- creating a record for someone else must not have it silently linked to
-- their own sales row.
--

create table public.employees (
    id bigint generated by default as identity primary key,
    sales_id bigint unique,
    first_name text not null,
    last_name text not null,
    email extensions.citext,
    phone text,
    employee_code text,
    department text,
    designation text,
    employment_type text,
    status text not null default 'active',
    date_of_joining date not null default current_date,
    date_of_leaving date,
    avatar jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.employees
    add constraint employees_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

create unique index employees_employee_code_uq on public.employees (employee_code) where employee_code is not null;

-- RLS: direct-owned pattern (like companies) — visible to the linked sales
-- user or any admin; only admins can create/delete.
alter table public.employees enable row level security;

create policy "Select own or admin" on public.employees for select to authenticated
    using (public.is_admin() or sales_id = public.current_sales_id());
create policy "Admin create only" on public.employees for insert to authenticated
    with check (public.is_admin());
create policy "Update own or admin" on public.employees for update to authenticated
    using (public.is_admin() or sales_id = public.current_sales_id())
    with check (public.is_admin() or sales_id = public.current_sales_id());
create policy "Admin delete only" on public.employees for delete to authenticated
    using (public.is_admin());

grant all on table public.employees to anon;
grant all on table public.employees to authenticated;
grant all on table public.employees to service_role;

grant all on sequence public.employees_id_seq to anon;
grant all on sequence public.employees_id_seq to authenticated;
grant all on sequence public.employees_id_seq to service_role;
