--
-- Personal Notes: Google-Keep-style personal note-taking, inspired by
-- bretzel-app/crumbs. Self-owned like companies/deals, but unlike every
-- other table in this schema, delete does NOT require admin — these are
-- private scratch content, not shared business/HR data, so a user must be
-- able to delete their own note without an admin.
--

create table public.personal_notes (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    title text,
    content text,
    type text not null default 'note',
    checklist_items jsonb not null default '[]',
    tags bigint[],
    color text,
    pinned boolean not null default false,
    archived_at timestamp with time zone,
    deleted_at timestamp with time zone,
    attachments jsonb[],
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint personal_notes_type_check check (type in ('note', 'checklist'))
);

alter table public.personal_notes
    add constraint personal_notes_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete cascade;

create index personal_notes_sales_id_idx on public.personal_notes using btree (sales_id);

create trigger set_personal_note_sales_id_trigger before insert on public.personal_notes
    for each row execute function public.set_sales_id_default();

alter table public.personal_notes enable row level security;

create policy "Select own or admin" on public.personal_notes for select to authenticated
    using (public.is_admin() or sales_id = public.current_sales_id());
create policy "Insert own or admin" on public.personal_notes for insert to authenticated
    with check (public.is_admin() or sales_id = public.current_sales_id());
create policy "Update own or admin" on public.personal_notes for update to authenticated
    using (public.is_admin() or sales_id = public.current_sales_id())
    with check (public.is_admin() or sales_id = public.current_sales_id());
create policy "Delete own or admin" on public.personal_notes for delete to authenticated
    using (public.is_admin() or sales_id = public.current_sales_id());

grant all on table public.personal_notes to anon;
grant all on table public.personal_notes to authenticated;
grant all on table public.personal_notes to service_role;

grant all on sequence public.personal_notes_id_seq to anon;
grant all on sequence public.personal_notes_id_seq to authenticated;
grant all on sequence public.personal_notes_id_seq to service_role;
