-- Comments on assignments (tasks), mirrors issue_notes -- no attachments
-- for v1, not requested.
create table public.assignment_notes (
    id bigint generated by default as identity primary key,
    assignment_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint
);
alter table public.assignment_notes
    add constraint assignment_notes_assignment_id_fkey foreign key (assignment_id) references public.assignments(id) on delete cascade;
alter table public.assignment_notes
    add constraint assignment_notes_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;
create index assignment_notes_assignment_id_idx on public.assignment_notes using btree (assignment_id);

create or replace trigger set_assignment_notes_sales_id_trigger before insert on public.assignment_notes
    for each row execute function public.set_sales_id_default();

-- Shared by assignment_notes' RLS policies, same reason can_access_project() exists.
create or replace function public.can_access_assignment(p_assignment_id bigint) returns boolean
    language sql stable security definer
    set search_path = ''
    as $$
  select exists (
    select 1 from public.assignments a
    where a.id = p_assignment_id
      and (public.is_admin() or a.sales_id = public.current_sales_id() or a.assignee_id = public.current_sales_id())
  );
$$;

alter table public.assignment_notes enable row level security;
create policy "Select via assignment access" on public.assignment_notes for select to authenticated using (
    public.can_access_assignment(assignment_id)
);
create policy "Insert via assignment access, not notes-only" on public.assignment_notes for insert to authenticated with check (
    not public.is_notes_only() and public.can_access_assignment(assignment_id)
);
create policy "Update own or admin" on public.assignment_notes for update to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id()
) with check (
    public.is_admin() or sales_id = public.current_sales_id()
);
create policy "Admin delete only" on public.assignment_notes for delete to authenticated using (public.is_admin());

grant all on table public.assignment_notes to anon;
grant all on table public.assignment_notes to authenticated;
grant all on table public.assignment_notes to service_role;
grant all on sequence public.assignment_notes_id_seq to anon;
grant all on sequence public.assignment_notes_id_seq to authenticated;
grant all on sequence public.assignment_notes_id_seq to service_role;
