--
-- HRMS: Leave requests
-- join-through RLS to employees.sales_id (like tasks -> contacts): a
-- self-service user can submit/cancel their own pending requests but
-- cannot self-approve, since approve/reject requires is_admin().
--

create table public.leave_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    leave_type text not null,
    from_date date not null,
    to_date date not null,
    days smallint generated always as ((to_date - from_date) + 1) stored,
    reason text,
    status text not null default 'pending',
    approved_by bigint,
    approved_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint leave_requests_dates_check check (to_date >= from_date),
    constraint leave_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

alter table public.leave_requests
    add constraint leave_requests_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;
alter table public.leave_requests
    add constraint leave_requests_approved_by_fkey foreign key (approved_by) references public.sales(id);

create index leave_requests_employee_id_idx on public.leave_requests using btree (employee_id);

alter table public.leave_requests enable row level security;

create policy "Select own or admin" on public.leave_requests for select to authenticated
    using (public.is_admin() or exists (
        select 1 from public.employees e where e.id = leave_requests.employee_id and e.sales_id = public.current_sales_id()
    ));

create policy "Insert own pending or admin" on public.leave_requests for insert to authenticated
    with check (
        public.is_admin()
        or (
            exists (select 1 from public.employees e where e.id = leave_requests.employee_id and e.sales_id = public.current_sales_id())
            and status = 'pending' and approved_by is null and approved_at is null
        )
    );

create policy "Update own pending or admin" on public.leave_requests for update to authenticated
    using (
        public.is_admin()
        or (
            exists (select 1 from public.employees e where e.id = leave_requests.employee_id and e.sales_id = public.current_sales_id())
            and status = 'pending'
        )
    )
    with check (
        public.is_admin()
        or (status in ('pending', 'cancelled') and approved_by is null and approved_at is null)
    );

create policy "Admin delete only" on public.leave_requests for delete to authenticated
    using (public.is_admin());

grant all on table public.leave_requests to anon;
grant all on table public.leave_requests to authenticated;
grant all on table public.leave_requests to service_role;

grant all on sequence public.leave_requests_id_seq to anon;
grant all on sequence public.leave_requests_id_seq to authenticated;
grant all on sequence public.leave_requests_id_seq to service_role;
