-- Photo delivery prototype for a photographer client: galleries
-- (client folders) with a random share_token for the client-facing
-- view, and the photos in each. Photos are uploaded to Google Drive
-- via the existing google_drive_upload function -- these tables just
-- track the folder structure and the returned Drive links.
-- Team-shared, not personal: any non-notes-only sales user can manage
-- any gallery (same shape as companies/contacts), delete stays
-- admin-only. The client-facing view never queries these tables
-- directly (that would let anon enumerate every client's photos) --
-- it goes through a dedicated edge function that looks up one gallery
-- by its exact share_token, service-role, same trust model as any
-- "anyone with the link" share.

create table public.photo_galleries (
    id bigint generated by default as identity primary key,
    name text not null,
    client_name text,
    share_token text not null unique,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.gallery_photos (
    id bigint generated by default as identity primary key,
    gallery_id bigint not null,
    drive_file_id text not null,
    src text not null,
    mime_type text,
    filename text,
    sales_id bigint,
    created_at timestamp with time zone not null default now()
);

alter table public.gallery_photos
    add constraint gallery_photos_gallery_id_fkey foreign key (gallery_id) references public.photo_galleries(id) on delete cascade;
alter table public.photo_galleries
    add constraint photo_galleries_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;
alter table public.gallery_photos
    add constraint gallery_photos_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete set null;

create index gallery_photos_gallery_id_idx on public.gallery_photos using btree (gallery_id);

alter table public.photo_galleries enable row level security;
alter table public.gallery_photos enable row level security;

create policy "Team access, not notes-only" on public.photo_galleries for select to authenticated using (not public.is_notes_only());
create policy "Team insert, not notes-only" on public.photo_galleries for insert to authenticated with check (not public.is_notes_only());
create policy "Team update, not notes-only" on public.photo_galleries for update to authenticated using (not public.is_notes_only()) with check (not public.is_notes_only());
create policy "Admin delete only" on public.photo_galleries for delete to authenticated using (public.is_admin());

create policy "Team access, not notes-only" on public.gallery_photos for select to authenticated using (not public.is_notes_only());
create policy "Team insert, not notes-only" on public.gallery_photos for insert to authenticated with check (not public.is_notes_only());
create policy "Team update, not notes-only" on public.gallery_photos for update to authenticated using (not public.is_notes_only()) with check (not public.is_notes_only());
create policy "Admin delete only" on public.gallery_photos for delete to authenticated using (public.is_admin());

create trigger set_photo_gallery_sales_id_trigger
    before insert on public.photo_galleries
    for each row execute function public.set_sales_id_default();

create trigger set_gallery_photo_sales_id_trigger
    before insert on public.gallery_photos
    for each row execute function public.set_sales_id_default();

grant all on table public.photo_galleries to authenticated;
grant all on table public.photo_galleries to service_role;
grant all on table public.gallery_photos to authenticated;
grant all on table public.gallery_photos to service_role;
-- These aren't meant to be anon-reachable at all (see the header
-- comment) -- revoke the standing default-privilege grant that
-- auto-applies to anon on any new table, same as oauth_tokens.
revoke all on table public.photo_galleries from anon;
revoke all on table public.gallery_photos from anon;

grant all on sequence public.photo_galleries_id_seq to authenticated;
grant all on sequence public.photo_galleries_id_seq to service_role;
grant all on sequence public.gallery_photos_id_seq to authenticated;
grant all on sequence public.gallery_photos_id_seq to service_role;
revoke all on sequence public.photo_galleries_id_seq from anon;
revoke all on sequence public.gallery_photos_id_seq from anon;
