-- Three additions to the photo-gallery prototype:
--   1. Photographers can now be given their own login (a `sales` row
--      with is_photographer=true, linked back via
--      photographers.login_sales_id) so they can manage their own
--      clients/albums/photos directly instead of the admin doing it
--      for them. Every other role keeps its existing team-wide access
--      to all photographers -- this only *adds* a narrower role.
--   2. A new "gallery_albums" level between a client gallery and its
--      photos (e.g. "Outdoor"/"Indoor" folders for one client), so
--      Drive folders now nest photographer/gallery/album. Existing
--      photos (uploaded before albums existed) are backfilled into a
--      generated "All Photos" album per gallery rather than deleted.
--   3. gallery_photos.size_bytes, captured at upload time, so storage
--      used per photographer can be totalled (photographer_storage_usage
--      view below).

alter table public.sales add column is_photographer boolean not null default false;

alter table public.photographers
    add column login_sales_id bigint;
alter table public.photographers
    add constraint photographers_login_sales_id_fkey foreign key (login_sales_id) references public.sales(id) on delete set null;
create unique index photographers_login_sales_id_key on public.photographers using btree (login_sales_id);

create table public.gallery_albums (
    id bigint generated by default as identity primary key,
    gallery_id bigint not null references public.photo_galleries(id) on delete cascade,
    name text not null,
    -- Cached Drive subfolder id (under the gallery's own folder), created on first upload.
    drive_folder_id text,
    sales_id bigint references public.sales(id) on delete set null,
    created_at timestamp with time zone not null default now()
);

create index gallery_albums_gallery_id_idx on public.gallery_albums using btree (gallery_id);

-- One generated album per gallery that already had photos, so the
-- handful of test uploads from before albums existed keep working
-- instead of being deleted.
insert into public.gallery_albums (gallery_id, name)
select distinct gallery_id, 'All Photos' from public.gallery_photos;

alter table public.gallery_photos add column album_id bigint;
update public.gallery_photos gp
set album_id = ga.id
from public.gallery_albums ga
where ga.gallery_id = gp.gallery_id and ga.name = 'All Photos';

alter table public.gallery_photos drop constraint gallery_photos_gallery_id_fkey;
drop index public.gallery_photos_gallery_id_idx;
alter table public.gallery_photos drop column gallery_id;
alter table public.gallery_photos
    alter column album_id set not null,
    add constraint gallery_photos_album_id_fkey foreign key (album_id) references public.gallery_albums(id) on delete cascade,
    add column size_bytes bigint;
create index gallery_photos_album_id_idx on public.gallery_photos using btree (album_id);

alter table public.gallery_albums enable row level security;

-- Role/ownership helpers -----------------------------------------------

create or replace function public.is_photographer() returns boolean
    language plpgsql security definer
    set search_path to ''
    as $$
begin
  return exists (
    select 1 from public.sales where user_id = auth.uid() and is_photographer = true
  );
end;
$$;

-- The photographer record (if any) this logged-in account IS, as
-- opposed to photographers.sales_id (who created the record).
create or replace function public.current_photographer_id() returns bigint
    language sql stable security definer
    set search_path to ''
    as $$
  select p.id from public.photographers p
  join public.sales s on s.id = p.login_sales_id
  where s.user_id = auth.uid();
$$;

create or replace function public.owns_photographer(p_photographer_id bigint) returns boolean
    language sql stable security definer
    set search_path to ''
    as $$
  select public.is_photographer() and p_photographer_id = public.current_photographer_id();
$$;

create or replace function public.gallery_photographer_id(p_gallery_id bigint) returns bigint
    language sql stable security definer
    set search_path to ''
    as $$
  select photographer_id from public.photo_galleries where id = p_gallery_id;
$$;

create or replace function public.album_photographer_id(p_album_id bigint) returns bigint
    language sql stable security definer
    set search_path to ''
    as $$
  select pg.photographer_id
  from public.gallery_albums ga
  join public.photo_galleries pg on pg.id = ga.gallery_id
  where ga.id = p_album_id;
$$;

-- Policies ---------------------------------------------------------------
-- Every existing team role keeps seeing/managing every photographer's
-- data exactly as before (not is_notes_only()). The only new
-- restriction: an is_photographer() login only sees/manages rows that
-- are their OWN (owns_photographer()) -- everyone else is unaffected.

drop policy "Team access, not notes-only" on public.photographers;
drop policy "Team insert, not notes-only" on public.photographers;
drop policy "Team update, not notes-only" on public.photographers;

create policy "Team access, own if photographer" on public.photographers for select to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or id = public.current_photographer_id()));
create policy "Team insert, not photographer" on public.photographers for insert to authenticated
    with check (not public.is_notes_only() and not public.is_photographer());
create policy "Team update, not photographer" on public.photographers for update to authenticated
    using (not public.is_notes_only() and not public.is_photographer())
    with check (not public.is_notes_only() and not public.is_photographer());

drop policy "Team access, not notes-only" on public.photo_galleries;
drop policy "Team insert, not notes-only" on public.photo_galleries;
drop policy "Team update, not notes-only" on public.photo_galleries;
drop policy "Admin delete only" on public.photo_galleries;

create policy "Team access, own if photographer" on public.photo_galleries for select to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(photographer_id)));
create policy "Team insert, own if photographer" on public.photo_galleries for insert to authenticated
    with check (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(photographer_id)));
create policy "Team update, own if photographer" on public.photo_galleries for update to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(photographer_id)))
    with check (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(photographer_id)));
create policy "Admin or own photographer delete" on public.photo_galleries for delete to authenticated
    using (public.is_admin() or public.owns_photographer(photographer_id));

create policy "Team access, own if photographer" on public.gallery_albums for select to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.gallery_photographer_id(gallery_id))));
create policy "Team insert, own if photographer" on public.gallery_albums for insert to authenticated
    with check (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.gallery_photographer_id(gallery_id))));
create policy "Team update, own if photographer" on public.gallery_albums for update to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.gallery_photographer_id(gallery_id))))
    with check (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.gallery_photographer_id(gallery_id))));
create policy "Admin or own photographer delete" on public.gallery_albums for delete to authenticated
    using (public.is_admin() or public.owns_photographer(public.gallery_photographer_id(gallery_id)));

drop policy "Team access, not notes-only" on public.gallery_photos;
drop policy "Team insert, not notes-only" on public.gallery_photos;
drop policy "Team update, not notes-only" on public.gallery_photos;
drop policy "Admin delete only" on public.gallery_photos;

create policy "Team access, own if photographer" on public.gallery_photos for select to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.album_photographer_id(album_id))));
create policy "Team insert, own if photographer" on public.gallery_photos for insert to authenticated
    with check (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.album_photographer_id(album_id))));
create policy "Team update, own if photographer" on public.gallery_photos for update to authenticated
    using (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.album_photographer_id(album_id))))
    with check (not public.is_notes_only() and (not public.is_photographer() or public.owns_photographer(public.album_photographer_id(album_id))));
create policy "Admin or own photographer delete" on public.gallery_photos for delete to authenticated
    using (public.is_admin() or public.owns_photographer(public.album_photographer_id(album_id)));

create trigger set_gallery_album_sales_id_trigger
    before insert on public.gallery_albums
    for each row execute function public.set_sales_id_default();

grant all on table public.gallery_albums to authenticated;
grant all on table public.gallery_albums to service_role;
revoke all on table public.gallery_albums from anon;

grant all on sequence public.gallery_albums_id_seq to authenticated;
grant all on sequence public.gallery_albums_id_seq to service_role;
revoke all on sequence public.gallery_albums_id_seq from anon;

-- Per-photographer storage usage, for display on their detail page.
-- security_invoker so RLS on the underlying tables still applies to
-- whoever queries the view -- without it, a photographer-role login
-- would see every photographer's total, not just their own.
create view public.photographer_storage_usage
    with (security_invoker = true) as
select
    ph.id,
    coalesce(sum(gp.size_bytes), 0)::bigint as total_bytes,
    count(gp.id) as photo_count
from public.photographers ph
left join public.photo_galleries pg on pg.photographer_id = ph.id
left join public.gallery_albums ga on ga.gallery_id = pg.id
left join public.gallery_photos gp on gp.album_id = ga.id
group by ph.id;

grant select on public.photographer_storage_usage to authenticated;
grant select on public.photographer_storage_usage to service_role;
revoke all on public.photographer_storage_usage from anon;
