--
-- PM: sprints (#67). Time-boxed grouping of issues per project. Same
-- has_pm_access() RLS pattern as projects/issues -- admin or developer,
-- admin-only delete.
--

create table public.sprints (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name text not null,
    start_date date,
    end_date date,
    status text not null default 'planned',
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    constraint sprints_status_check check (status in ('planned', 'active', 'completed'))
);

alter table public.sprints
    add constraint sprints_project_id_fkey foreign key (project_id) references public.projects(id) on update cascade on delete cascade;

create index sprints_project_id_idx on public.sprints using btree (project_id);

create or replace trigger set_sprint_sales_id_trigger
    before insert on public.sprints
    for each row execute function public.set_sales_id_default();

alter table public.sprints enable row level security;
create policy "PM access select" on public.sprints for select to authenticated using (public.has_pm_access());
create policy "PM access insert" on public.sprints for insert to authenticated with check (public.has_pm_access());
create policy "PM access update" on public.sprints for update to authenticated using (public.has_pm_access()) with check (public.has_pm_access());
create policy "Admin delete only" on public.sprints for delete to authenticated using (public.is_admin());

grant all on table public.sprints to anon;
grant all on table public.sprints to authenticated;
grant all on table public.sprints to service_role;
grant all on sequence public.sprints_id_seq to anon;
grant all on sequence public.sprints_id_seq to authenticated;
grant all on sequence public.sprints_id_seq to service_role;

alter table public.issues add column sprint_id bigint;
alter table public.issues
    add constraint issues_sprint_id_fkey foreign key (sprint_id) references public.sprints(id) on delete set null;
