--
-- Personal Notes: version history. Populated automatically via a BEFORE
-- UPDATE trigger that snapshots the OLD row whenever a meaningful field
-- changes (title/content/type/checklist_items/tags/color) — not on every
-- pin/archive toggle, which would spam versions for no reason.
--

create table public.personal_note_versions (
    id bigint generated by default as identity primary key,
    note_id bigint not null,
    title text,
    content text,
    type text not null,
    checklist_items jsonb not null default '[]',
    tags bigint[],
    color text,
    created_at timestamp with time zone not null default now()
);

alter table public.personal_note_versions
    add constraint personal_note_versions_note_id_fkey foreign key (note_id) references public.personal_notes(id) on update cascade on delete cascade;

create index personal_note_versions_note_id_idx on public.personal_note_versions using btree (note_id);

create or replace function public.snapshot_personal_note_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if (old.title is distinct from new.title)
     or (old.content is distinct from new.content)
     or (old.type is distinct from new.type)
     or (old.checklist_items is distinct from new.checklist_items)
     or (old.tags is distinct from new.tags)
     or (old.color is distinct from new.color) then
    insert into public.personal_note_versions (note_id, title, content, type, checklist_items, tags, color)
    values (old.id, old.title, old.content, old.type, old.checklist_items, old.tags, old.color);
  end if;
  return new;
end;
$$;

create trigger snapshot_personal_note_version_trigger
    before update on public.personal_notes
    for each row execute function public.snapshot_personal_note_version();

alter table public.personal_note_versions enable row level security;

create policy "Select own or admin" on public.personal_note_versions for select to authenticated
    using (public.is_admin() or exists (
        select 1 from public.personal_notes pn where pn.id = personal_note_versions.note_id and pn.sales_id = public.current_sales_id()
    ));
create policy "Insert own or admin" on public.personal_note_versions for insert to authenticated
    with check (public.is_admin() or exists (
        select 1 from public.personal_notes pn where pn.id = note_id and pn.sales_id = public.current_sales_id()
    ));
create policy "Delete own or admin" on public.personal_note_versions for delete to authenticated
    using (public.is_admin() or exists (
        select 1 from public.personal_notes pn where pn.id = personal_note_versions.note_id and pn.sales_id = public.current_sales_id()
    ));

grant all on function public.snapshot_personal_note_version() to anon;
grant all on function public.snapshot_personal_note_version() to authenticated;
grant all on function public.snapshot_personal_note_version() to service_role;

grant all on table public.personal_note_versions to anon;
grant all on table public.personal_note_versions to authenticated;
grant all on table public.personal_note_versions to service_role;

grant all on sequence public.personal_note_versions_id_seq to anon;
grant all on sequence public.personal_note_versions_id_seq to authenticated;
grant all on sequence public.personal_note_versions_id_seq to service_role;
