-- Personal weekly planner: time-blocked tasks (an addition to the
-- existing assignments table), a per-week "focus" note, and a daily
-- review/journal. All owner-only, mirrors personal_notes' RLS shape --
-- not shared, not gated by role beyond notes-only (same as assignments).

alter table public.assignments
    add column time_block text,
    add column blocked_on text;

alter table public.assignments
    add constraint assignments_time_block_check check (
        time_block is null or time_block in (
            'fajr_quran',
            'morning_prep',
            'deep_work_1',
            'sales_comm',
            'buffer',
            'deep_work_2',
            'learning',
            'exercise',
            'evening_personal',
            'evening_review'
        )
    );

create table public.weekly_plans (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    week_start date not null,
    focus text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint weekly_plans_sales_week_unique unique (sales_id, week_start)
);

create table public.daily_reviews (
    id bigint generated by default as identity primary key,
    sales_id bigint not null,
    date date not null,
    completed text,
    blocked text,
    changed text,
    avoid_tomorrow text,
    top3_tomorrow text[] not null default '{}',
    if_time_allows text[] not null default '{}',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint daily_reviews_sales_date_unique unique (sales_id, date)
);

alter table public.weekly_plans
    add constraint weekly_plans_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete cascade;

alter table public.daily_reviews
    add constraint daily_reviews_sales_id_fkey foreign key (sales_id) references public.sales(id) on delete cascade;

alter table public.weekly_plans enable row level security;
alter table public.daily_reviews enable row level security;

create policy "Select own or admin" on public.weekly_plans for select to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id()
);
create policy "Insert own or admin, not notes-only" on public.weekly_plans for insert to authenticated with check (
    (public.is_admin() or sales_id = public.current_sales_id()) and not public.is_notes_only()
);
create policy "Update own or admin, not notes-only" on public.weekly_plans for update to authenticated using (
    (public.is_admin() or sales_id = public.current_sales_id()) and not public.is_notes_only()
) with check (
    (public.is_admin() or sales_id = public.current_sales_id()) and not public.is_notes_only()
);
create policy "Delete own or admin" on public.weekly_plans for delete to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id()
);

create policy "Select own or admin" on public.daily_reviews for select to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id()
);
create policy "Insert own or admin, not notes-only" on public.daily_reviews for insert to authenticated with check (
    (public.is_admin() or sales_id = public.current_sales_id()) and not public.is_notes_only()
);
create policy "Update own or admin, not notes-only" on public.daily_reviews for update to authenticated using (
    (public.is_admin() or sales_id = public.current_sales_id()) and not public.is_notes_only()
) with check (
    (public.is_admin() or sales_id = public.current_sales_id()) and not public.is_notes_only()
);
create policy "Delete own or admin" on public.daily_reviews for delete to authenticated using (
    public.is_admin() or sales_id = public.current_sales_id()
);

create trigger set_weekly_plan_sales_id_trigger
    before insert on public.weekly_plans
    for each row execute function public.set_sales_id_default();

create trigger set_daily_review_sales_id_trigger
    before insert on public.daily_reviews
    for each row execute function public.set_sales_id_default();

grant all on table public.weekly_plans to anon;
grant all on table public.weekly_plans to authenticated;
grant all on table public.weekly_plans to service_role;

grant all on table public.daily_reviews to anon;
grant all on table public.daily_reviews to authenticated;
grant all on table public.daily_reviews to service_role;

grant all on sequence public.weekly_plans_id_seq to anon;
grant all on sequence public.weekly_plans_id_seq to authenticated;
grant all on sequence public.weekly_plans_id_seq to service_role;

grant all on sequence public.daily_reviews_id_seq to anon;
grant all on sequence public.daily_reviews_id_seq to authenticated;
grant all on sequence public.daily_reviews_id_seq to service_role;
