--
-- HRMS: Attendance
-- join-through RLS to employees.sales_id (like leave_requests). No
-- approval workflow in v1: self can log/edit their own rows freely.
--

create table public.attendance_records (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    date date not null,
    status text not null default 'present',
    check_in timestamp with time zone,
    check_out timestamp with time zone,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.attendance_records
    add constraint attendance_records_employee_id_fkey foreign key (employee_id) references public.employees(id) on update cascade on delete cascade;

create unique index attendance_records_employee_date_uq on public.attendance_records (employee_id, date);

alter table public.attendance_records enable row level security;

create policy "Select own or admin" on public.attendance_records for select to authenticated
    using (public.is_admin() or exists (
        select 1 from public.employees e where e.id = attendance_records.employee_id and e.sales_id = public.current_sales_id()
    ));
create policy "Insert own or admin" on public.attendance_records for insert to authenticated
    with check (public.is_admin() or exists (
        select 1 from public.employees e where e.id = attendance_records.employee_id and e.sales_id = public.current_sales_id()
    ));
create policy "Update own or admin" on public.attendance_records for update to authenticated
    using (public.is_admin() or exists (
        select 1 from public.employees e where e.id = attendance_records.employee_id and e.sales_id = public.current_sales_id()
    ));
create policy "Admin delete only" on public.attendance_records for delete to authenticated
    using (public.is_admin());

grant all on table public.attendance_records to anon;
grant all on table public.attendance_records to authenticated;
grant all on table public.attendance_records to service_role;

grant all on sequence public.attendance_records_id_seq to anon;
grant all on sequence public.attendance_records_id_seq to authenticated;
grant all on sequence public.attendance_records_id_seq to service_role;
